<?php /*	if ($Conf -> validTimeFor('authorViewReviews', 0)) {
	    print "<td>";
	    $Conf->linkWithPaperId("See Reviews",
				   "Author/ViewReview.php",
				   $id);
	    print "</td>";
	}

	if ($Conf -> validTimeFor('authorRespondToReviews', 0)) {
	    print "<td>";
	    $Conf->linkWithPaperId("Respond To Reviews",
				   "Author/SubmitResponse.php",
				   $id);
	    print "</td>";
	}
	
	if ($Conf -> validTimeFor('authorViewDecision', 0)) {
	    print "<td>";
	    $Conf->linkWithPaperId("See Paper Outcome",
				   "Author/ViewDecision.php",
				   $id);
	    print "</td>";
	}
      */ ?>