<?php $Conf -> taskHeader("Tasks for Everyone", $TaskSpan); ?>

<ul>
<li> <a href="<?php echo $AllPrefix ?>Logout.php"> Log out  </a> of your account </li>
<li> <a href="<?php echo $AllPrefix ?>UpdateContactInfo.php"> Update </a> your account information  </li>
<li> <a href="<?php echo $AllPrefix ?>MergeAccounts.php"> Merge </a> account information </li>
<li> <a href="<?php echo $AllPrefix ?>ImportantDates.php"> See </a> important dates </li>
</ul>
